=== lxyqaq/html_css/Lab/XML2/book.dtd
<!ELEMENT books (book+)>
        <!ELEMENT book (title,chapter+,price)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT chapter (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ATTLIST book
                publisher (Pearson | Wiley) #REQUIRED
                author CDATA #REQUIRED>
        <!ATTLIST chapter chNo CDATA #REQUIRED>
        <!ATTLIST price currency (euro | dollar) #IMPLIED>

=== lxyqaq/html_css/Lab/XML2/books.xml
<!DOCTYPE books SYSTEM "book.dtd">
<books>
    <book publisher="Wiley" author="Paul">
        <title>XML</title>
        <chapter chNo="1">This is chapter 1</chapter>
        <chapter chNo="2">This is chapter 2</chapter>
        <price currency="euro">50</price>
    </book>
    <book publisher="Pearson" author="John Sweeney">
        <title>REST</title>
        <chapter chNo="1">This is chapter 1</chapter>
        <chapter chNo="2">This is chapter 2</chapter>
        <price>60</price>
    </book>
</books>
