=== lxyqaq/html_css/Lab/XML2/grocery.dtd
<!ELEMENT grocery-list (veggies,meat,dairyProducts,misc)>
        <!ELEMENT veggies (item+)>
        <!ELEMENT meat (item+)>
        <!ELEMENT dairyProducts (item+)>
        <!ELEMENT misc (item+)>
        <!ELEMENT item (#PCDATA)>

=== lxyqaq/html_css/Lab/XML2/grocery-list.xml
<?xml version="1.0"?>
<!DOCTYPE grocery-list SYSTEM "grocery.dtd">
<grocery-list>
    <veggies>
        <item>lettuce</item>
        <item>tomatoes</item>
        <item>onion</item>
    </veggies>
    <meat>
        <item>chicken</item>
        <item>beef</item>
    </meat>
    <dairyProducts>
        <item>cheese</item>
    </dairyProducts>
    <misc>
        <item>bread</item>
        <item>eggs</item>
    </misc>
</grocery-list>
